---

# mariadb
- name: Add MariaDB repo
  template: src=yum.repos.d/mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo
    owner=root group=root mode=0644


- name: Extract MariaDB packages
  unarchive:
    src=mariadb.tar.gz
    dest=/media/
