---
- name: Ensuring config directories exist
  file:
    path: "/etc/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "keepalived"
    - "haproxy"

- name: Copying over check_alive.sh
  template:
    src: "{{ item }}"
    dest: "/check_alive.sh"
    mode: 0755
  with_items:
    - "check_alive.sh.j2"

- name: Copying over haproxy.cfg
  template:
    src: "{{ item }}"
    dest: "/etc/haproxy/haproxy.cfg"
  with_items:
    - "haproxy.cfg.j2"
  notify: restart haproxy

- name: Copying over keepalived.conf
  template:
    src: "{{ item }}"
    dest: "/etc/keepalived/keepalived.conf"
  with_items:
    - "keepalived.conf.j2"
  notify: restart keepalived

