---
#
- name: Starting keepalived
  service:
    name: keepalived
    state: started
    enabled: yes

#
- name: Starting haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

#
- name: Waiting for virtual IP to appear
  wait_for:
    host: "{{ vip_address }}"
    port: "{{ mariadb_port }}"
