---
- hosts: all
  roles:

    - { role: createHosts, tags: ['setup'] }
    - { role: security, tags: ['setup'] }
    - { role: repos, tags: ['setup', 'packages'] }
    - { role: packages, tags: ['setup', 'packages'] }

- hosts: haproxy
  roles:
    - haproxy



- hosts: mariadb
  roles:
    - galera