---
- name: Disable firewalld
  service: name={{ item }} state=stopped enabled=no
  with_items:
   - firewalld
   - NetworkManager

# Disable SELinux
- name: Disable SELinux
  selinux: state=disabled

# setting sysctl values
- name: Setting sysctl values
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=no reload=yes
  with_items:
    - { name: "net.ipv4.ip_nonlocal_bind", value: 1}
    - { name: "net.unix.max_dgram_qlen", value: 128}
    - { name: "net.bridge.bridge-nf-call-iptables", value: 1}
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1}
    - { name: "net.ipv4.conf.all.rp_filter", value: 0}
    - { name: "net.ipv4.conf.default.rp_filter", value: 0}
    - { name: "net.ipv4.ip_forward", value: 0}
