---
- name: Creating haproxy mysql user

  shell: mysql -u{{ mariadb_user }} -p{{ mariadb_passwd }} -e "{{ item }}" 
  with_items:

    - "CREATE USER 'haproxy'@'%' IDENTIFIED BY '';"
    - "flush privileges;"

  run_once: True

